# Generated by Django 4.2.7 on 2023-11-22 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('pais', models.CharField(max_length=25)),
                ('ciudad', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=25)),
                ('fechaNacimiento', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('contrasena', models.CharField(max_length=25)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=55)),
                ('subtitulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('mililiter', models.IntegerField()),
                ('imagen', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('precioTotal', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abm.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abm.producto')),
            ],
        ),
    ]
