# Generated by Django 4.2.7 on 2023-11-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0002_remove_cliente_estado_remove_cliente_fechanacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='', upload_to='productos'),
        ),
    ]
